// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<Project>> getAllProjects() =>
    RustLib.instance.api.crateApiProjectsGetAllProjects();

Future<Project> createProject({
  required String name,
  required PlatformInt64 colorIndex,
}) => RustLib.instance.api.crateApiProjectsCreateProject(
  name: name,
  colorIndex: colorIndex,
);

Future<Project> updateProject({
  required String id,
  required String name,
  required PlatformInt64 colorIndex,
}) => RustLib.instance.api.crateApiProjectsUpdateProject(
  id: id,
  name: name,
  colorIndex: colorIndex,
);

Future<void> deleteProject({required String id}) =>
    RustLib.instance.api.crateApiProjectsDeleteProject(id: id);
