// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> getSyncState() =>
    RustLib.instance.api.crateApiSyncGetSyncState();

Future<void> setSyncState({required String json}) =>
    RustLib.instance.api.crateApiSyncSetSyncState(json: json);

Future<String> getOrCreateDeviceId() =>
    RustLib.instance.api.crateApiSyncGetOrCreateDeviceId();

Future<SyncSnapshotResult> createSnapshot({
  required List<int> key,
  required String dbPath,
  required String deviceId,
  required String deviceName,
  required PlatformInt64 schemaVersion,
  required String appVersion,
}) => RustLib.instance.api.crateApiSyncCreateSnapshot(
  key: key,
  dbPath: dbPath,
  deviceId: deviceId,
  deviceName: deviceName,
  schemaVersion: schemaVersion,
  appVersion: appVersion,
);

Future<PlatformInt64> installSnapshot({
  required List<int> encrypted,
  required String manifestJson,
  required List<int> key,
  required String dbPath,
}) => RustLib.instance.api.crateApiSyncInstallSnapshot(
  encrypted: encrypted,
  manifestJson: manifestJson,
  key: key,
  dbPath: dbPath,
);

class SyncSnapshotResult {
  final Uint8List encrypted;
  final String manifestJson;

  const SyncSnapshotResult({
    required this.encrypted,
    required this.manifestJson,
  });

  @override
  int get hashCode => encrypted.hashCode ^ manifestJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncSnapshotResult &&
          runtimeType == other.runtimeType &&
          encrypted == other.encrypted &&
          manifestJson == other.manifestJson;
}
