// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<Task>> getAllTasks() =>
    RustLib.instance.api.crateApiTasksGetAllTasks();

Future<Task> createTask({
  required String title,
  String? description,
  PlatformInt64? dueDate,
  required PlatformInt64 priority,
  required String projectId,
  PlatformInt64? reminderMinutes,
}) => RustLib.instance.api.crateApiTasksCreateTask(
  title: title,
  description: description,
  dueDate: dueDate,
  priority: priority,
  projectId: projectId,
  reminderMinutes: reminderMinutes,
);

Future<Task> updateTask({required String taskJson}) =>
    RustLib.instance.api.crateApiTasksUpdateTask(taskJson: taskJson);

Future<void> reorderTasks({required List<String> taskIds}) =>
    RustLib.instance.api.crateApiTasksReorderTasks(taskIds: taskIds);

Future<void> deleteTask({required String id}) =>
    RustLib.instance.api.crateApiTasksDeleteTask(id: id);

Future<void> clearCompleted() =>
    RustLib.instance.api.crateApiTasksClearCompleted();

Future<void> restoreTask({required String id}) =>
    RustLib.instance.api.crateApiTasksRestoreTask(id: id);
