// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'api/projects.dart';
import 'api/sync.dart';
import 'api/tasks.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -605016674;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'plans_core',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiTasksClearCompleted();

  Future<Project> crateApiProjectsCreateProject({
    required String name,
    required PlatformInt64 colorIndex,
  });

  Future<SyncSnapshotResult> crateApiSyncCreateSnapshot({
    required List<int> key,
    required String dbPath,
    required String deviceId,
    required String deviceName,
    required PlatformInt64 schemaVersion,
    required String appVersion,
  });

  Future<Task> crateApiTasksCreateTask({
    required String title,
    String? description,
    PlatformInt64? dueDate,
    required PlatformInt64 priority,
    required String projectId,
    PlatformInt64? reminderMinutes,
    String? recurrence,
  });

  Future<void> crateApiProjectsDeleteProject({required String id});

  Future<void> crateApiTasksDeleteTask({required String id});

  Future<List<Project>> crateApiProjectsGetAllProjects();

  Future<List<Task>> crateApiTasksGetAllTasks();

  Future<String> crateApiSyncGetOrCreateDeviceId();

  Future<String> crateApiSyncGetSyncState();

  Future<void> crateApiInitDatabase({required String path});

  Future<PlatformInt64> crateApiSyncInstallSnapshot({
    required List<int> encrypted,
    required String manifestJson,
    required List<int> key,
    required String dbPath,
  });

  Future<void> crateApiTasksReorderTasks({required List<String> taskIds});

  Future<void> crateApiTasksRestoreTask({required String id});

  Future<void> crateApiSyncSetSyncState({required String json});

  Future<Project> crateApiProjectsUpdateProject({
    required String id,
    required String name,
    required PlatformInt64 colorIndex,
  });

  Future<Task> crateApiTasksUpdateTask({required String taskJson});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiTasksClearCompleted() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTasksClearCompletedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTasksClearCompletedConstMeta =>
      const TaskConstMeta(debugName: "clear_completed", argNames: []);

  @override
  Future<Project> crateApiProjectsCreateProject({
    required String name,
    required PlatformInt64 colorIndex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_i_64(colorIndex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_project,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProjectsCreateProjectConstMeta,
        argValues: [name, colorIndex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProjectsCreateProjectConstMeta =>
      const TaskConstMeta(
        debugName: "create_project",
        argNames: ["name", "colorIndex"],
      );

  @override
  Future<SyncSnapshotResult> crateApiSyncCreateSnapshot({
    required List<int> key,
    required String dbPath,
    required String deviceId,
    required String deviceName,
    required PlatformInt64 schemaVersion,
    required String appVersion,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_String(dbPath, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(deviceName, serializer);
          sse_encode_i_64(schemaVersion, serializer);
          sse_encode_String(appVersion, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sync_snapshot_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncCreateSnapshotConstMeta,
        argValues: [
          key,
          dbPath,
          deviceId,
          deviceName,
          schemaVersion,
          appVersion,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncCreateSnapshotConstMeta => const TaskConstMeta(
    debugName: "create_snapshot",
    argNames: [
      "key",
      "dbPath",
      "deviceId",
      "deviceName",
      "schemaVersion",
      "appVersion",
    ],
  );

  @override
  Future<Task> crateApiTasksCreateTask({
    required String title,
    String? description,
    PlatformInt64? dueDate,
    required PlatformInt64 priority,
    required String projectId,
    PlatformInt64? reminderMinutes,
    String? recurrence,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(title, serializer);
          sse_encode_opt_String(description, serializer);
          sse_encode_opt_box_autoadd_i_64(dueDate, serializer);
          sse_encode_i_64(priority, serializer);
          sse_encode_String(projectId, serializer);
          sse_encode_opt_box_autoadd_i_64(reminderMinutes, serializer);
          sse_encode_opt_String(recurrence, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_task,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTasksCreateTaskConstMeta,
        argValues: [
          title,
          description,
          dueDate,
          priority,
          projectId,
          reminderMinutes,
          recurrence,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTasksCreateTaskConstMeta => const TaskConstMeta(
    debugName: "create_task",
    argNames: [
      "title",
      "description",
      "dueDate",
      "priority",
      "projectId",
      "reminderMinutes",
      "recurrence",
    ],
  );

  @override
  Future<void> crateApiProjectsDeleteProject({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProjectsDeleteProjectConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProjectsDeleteProjectConstMeta =>
      const TaskConstMeta(debugName: "delete_project", argNames: ["id"]);

  @override
  Future<void> crateApiTasksDeleteTask({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTasksDeleteTaskConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTasksDeleteTaskConstMeta =>
      const TaskConstMeta(debugName: "delete_task", argNames: ["id"]);

  @override
  Future<List<Project>> crateApiProjectsGetAllProjects() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_project,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProjectsGetAllProjectsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProjectsGetAllProjectsConstMeta =>
      const TaskConstMeta(debugName: "get_all_projects", argNames: []);

  @override
  Future<List<Task>> crateApiTasksGetAllTasks() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_task,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTasksGetAllTasksConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTasksGetAllTasksConstMeta =>
      const TaskConstMeta(debugName: "get_all_tasks", argNames: []);

  @override
  Future<String> crateApiSyncGetOrCreateDeviceId() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncGetOrCreateDeviceIdConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncGetOrCreateDeviceIdConstMeta =>
      const TaskConstMeta(debugName: "get_or_create_device_id", argNames: []);

  @override
  Future<String> crateApiSyncGetSyncState() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncGetSyncStateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncGetSyncStateConstMeta =>
      const TaskConstMeta(debugName: "get_sync_state", argNames: []);

  @override
  Future<void> crateApiInitDatabase({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiInitDatabaseConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitDatabaseConstMeta =>
      const TaskConstMeta(debugName: "init_database", argNames: ["path"]);

  @override
  Future<PlatformInt64> crateApiSyncInstallSnapshot({
    required List<int> encrypted,
    required String manifestJson,
    required List<int> key,
    required String dbPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(encrypted, serializer);
          sse_encode_String(manifestJson, serializer);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_String(dbPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncInstallSnapshotConstMeta,
        argValues: [encrypted, manifestJson, key, dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncInstallSnapshotConstMeta =>
      const TaskConstMeta(
        debugName: "install_snapshot",
        argNames: ["encrypted", "manifestJson", "key", "dbPath"],
      );

  @override
  Future<void> crateApiTasksReorderTasks({required List<String> taskIds}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(taskIds, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTasksReorderTasksConstMeta,
        argValues: [taskIds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTasksReorderTasksConstMeta =>
      const TaskConstMeta(debugName: "reorder_tasks", argNames: ["taskIds"]);

  @override
  Future<void> crateApiTasksRestoreTask({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTasksRestoreTaskConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTasksRestoreTaskConstMeta =>
      const TaskConstMeta(debugName: "restore_task", argNames: ["id"]);

  @override
  Future<void> crateApiSyncSetSyncState({required String json}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(json, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncSetSyncStateConstMeta,
        argValues: [json],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncSetSyncStateConstMeta =>
      const TaskConstMeta(debugName: "set_sync_state", argNames: ["json"]);

  @override
  Future<Project> crateApiProjectsUpdateProject({
    required String id,
    required String name,
    required PlatformInt64 colorIndex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_String(name, serializer);
          sse_encode_i_64(colorIndex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_project,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProjectsUpdateProjectConstMeta,
        argValues: [id, name, colorIndex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProjectsUpdateProjectConstMeta =>
      const TaskConstMeta(
        debugName: "update_project",
        argNames: ["id", "name", "colorIndex"],
      );

  @override
  Future<Task> crateApiTasksUpdateTask({required String taskJson}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(taskJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_task,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTasksUpdateTaskConstMeta,
        argValues: [taskJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTasksUpdateTaskConstMeta =>
      const TaskConstMeta(debugName: "update_task", argNames: ["taskJson"]);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<Project> dco_decode_list_project(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_project).toList();
  }

  @protected
  List<Task> dco_decode_list_task(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_task).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  Project dco_decode_project(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Project(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      colorIndex: dco_decode_i_64(arr[2]),
    );
  }

  @protected
  SyncSnapshotResult dco_decode_sync_snapshot_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SyncSnapshotResult(
      encrypted: dco_decode_list_prim_u_8_strict(arr[0]),
      manifestJson: dco_decode_String(arr[1]),
    );
  }

  @protected
  Task dco_decode_task(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return Task(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      description: dco_decode_opt_String(arr[2]),
      dueDate: dco_decode_opt_box_autoadd_i_64(arr[3]),
      priority: dco_decode_i_64(arr[4]),
      isCompleted: dco_decode_bool(arr[5]),
      projectId: dco_decode_String(arr[6]),
      createdAt: dco_decode_i_64(arr[7]),
      updatedAt: dco_decode_i_64(arr[8]),
      sortOrder: dco_decode_i_64(arr[9]),
      reminderMinutes: dco_decode_opt_box_autoadd_i_64(arr[10]),
      recurrence: dco_decode_opt_String(arr[11]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<Project> sse_decode_list_project(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Project>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_project(deserializer));
    }
    return ans_;
  }

  @protected
  List<Task> sse_decode_list_task(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Task>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_task(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Project sse_decode_project(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_colorIndex = sse_decode_i_64(deserializer);
    return Project(id: var_id, name: var_name, colorIndex: var_colorIndex);
  }

  @protected
  SyncSnapshotResult sse_decode_sync_snapshot_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_encrypted = sse_decode_list_prim_u_8_strict(deserializer);
    var var_manifestJson = sse_decode_String(deserializer);
    return SyncSnapshotResult(
      encrypted: var_encrypted,
      manifestJson: var_manifestJson,
    );
  }

  @protected
  Task sse_decode_task(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_description = sse_decode_opt_String(deserializer);
    var var_dueDate = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_priority = sse_decode_i_64(deserializer);
    var var_isCompleted = sse_decode_bool(deserializer);
    var var_projectId = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    var var_updatedAt = sse_decode_i_64(deserializer);
    var var_sortOrder = sse_decode_i_64(deserializer);
    var var_reminderMinutes = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_recurrence = sse_decode_opt_String(deserializer);
    return Task(
      id: var_id,
      title: var_title,
      description: var_description,
      dueDate: var_dueDate,
      priority: var_priority,
      isCompleted: var_isCompleted,
      projectId: var_projectId,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
      sortOrder: var_sortOrder,
      reminderMinutes: var_reminderMinutes,
      recurrence: var_recurrence,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_project(List<Project> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_project(item, serializer);
    }
  }

  @protected
  void sse_encode_list_task(List<Task> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_task(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_project(Project self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_i_64(self.colorIndex, serializer);
  }

  @protected
  void sse_encode_sync_snapshot_result(
    SyncSnapshotResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.encrypted, serializer);
    sse_encode_String(self.manifestJson, serializer);
  }

  @protected
  void sse_encode_task(Task self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.description, serializer);
    sse_encode_opt_box_autoadd_i_64(self.dueDate, serializer);
    sse_encode_i_64(self.priority, serializer);
    sse_encode_bool(self.isCompleted, serializer);
    sse_encode_String(self.projectId, serializer);
    sse_encode_i_64(self.createdAt, serializer);
    sse_encode_i_64(self.updatedAt, serializer);
    sse_encode_i_64(self.sortOrder, serializer);
    sse_encode_opt_box_autoadd_i_64(self.reminderMinutes, serializer);
    sse_encode_opt_String(self.recurrence, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
