// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Project {
  final String id;
  final String name;
  final PlatformInt64 colorIndex;

  const Project({
    required this.id,
    required this.name,
    required this.colorIndex,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ colorIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Project &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          colorIndex == other.colorIndex;
}

class Task {
  final String id;
  final String title;
  final String? description;
  final PlatformInt64? dueDate;
  final PlatformInt64 priority;
  final bool isCompleted;
  final String projectId;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final PlatformInt64 sortOrder;
  final PlatformInt64? reminderMinutes;
  final String? recurrence;

  const Task({
    required this.id,
    required this.title,
    this.description,
    this.dueDate,
    required this.priority,
    required this.isCompleted,
    required this.projectId,
    required this.createdAt,
    required this.updatedAt,
    required this.sortOrder,
    this.reminderMinutes,
    this.recurrence,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      description.hashCode ^
      dueDate.hashCode ^
      priority.hashCode ^
      isCompleted.hashCode ^
      projectId.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      sortOrder.hashCode ^
      reminderMinutes.hashCode ^
      recurrence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Task &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          description == other.description &&
          dueDate == other.dueDate &&
          priority == other.priority &&
          isCompleted == other.isCompleted &&
          projectId == other.projectId &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          sortOrder == other.sortOrder &&
          reminderMinutes == other.reminderMinutes &&
          recurrence == other.recurrence;
}
